version = 0.1
[default.deploy.parameters]
stack_name = "pms2-app"
resolve_s3 = true
s3_prefix = "pms2-app"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
confirm_changeset = true
